version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REDIS_URL: ${REDIS_URL:-redis:6379}
      NODE_ENV: development
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - app
