version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=${REDIS_URL:-redis:6379}
      - NODE_ENV=development
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    command: go run main.go

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"

volumes:
  go-mod-cache:
