version: "3.7"

services:
  app:
    build: .
    environment:
      REDIS_URL: ${REDIS_URL:-redis:6379}
    ports:
      - 8080:8080

  redis:
    image: redis:5.0.7

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
