# fly.toml app configuration file generated for go-realtime-chat on 2024-11-11T14:58:18+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-realtime-chat'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[build.args]
  NODE_VERSION = "18"
  GO_VERSION = "1.22"

[env]
  NODE_ENV = 'production'
  GITHUB_CLIENT_ID = "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET = "${GITHUB_CLIENT_SECRET}"
  GRAPHQL_ENDPOINT = "/graphql"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
