services:
  - type: web
    name: fullstack-app
    env: docker
    buildCommand: docker build -t fullstack-app .
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: redis://localhost:6379